[package]
name = "raffia_codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raffia = "0.1.0"
codegen_macro = { path = "../codegen_macro/" }
clippy = "0.0.302"
bitflags = "1.3.2"

[dev-dependencies]
rusty-hook = "0.11.2"
testing = { path = "../testing/" }

[lib]
bench = false
