[package]
name = "testing"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
proc-macro2 = "1.0.46"
quote = "1.0"
syn = { version = "1.0.101", features = ["full"] }

[lib]
proc-macro = true
